language: csharp

dotnet: 2.1

dist: trusty

solution: ./src/MockQueryable/MockQueryable.sln

script:

  - cd src/MockQueryable

  - dotnet restore

  - dotnet build --configuration=Release

  - dotnet test ./MockQueryable.Sample/MockQueryable.Sample.csproj
  

